# Generated by Django 2.2.14 on 2021-02-14 21:50

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tableros', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lista',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('posicion', models.IntegerField(blank=True, null=True)),
                ('tablero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tableros.Tablero')),
            ],
        ),
    ]
