# Generated by Django 2.2.14 on 2021-02-15 09:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_auto_20210215_0307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='password',
            field=models.CharField(max_length=200, validators=[django.core.validators.MinLengthValidator(limit_value=8, message=None)]),
        ),
    ]
