# Generated by Django 2.2.14 on 2021-02-17 00:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_auto_20210215_0337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='email',
            field=models.CharField(max_length=200, unique=True, validators=[django.core.validators.EmailValidator(code=None, message=None, whitelist=None)]),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='username',
            field=models.CharField(default=models.CharField(max_length=200, unique=True, validators=[django.core.validators.EmailValidator(code=None, message=None, whitelist=None)]), max_length=200),
        ),
    ]
