# Generated by Django 2.2.14 on 2021-02-17 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0008_auto_20210216_1850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='username',
            field=models.CharField(default='', max_length=200),
        ),
    ]
